version: "2"
services:
  mariadb:
    image: mariadb:10.3
    env_file: .env
    ports:
      - $MYSQL_LISTEN_PORT:3306
    volumes:
      - ./mariadb/db:$MYSQL_DATA_DIR
      - ./mariadb/init:/docker-entrypoint-initdb.d
      - ./mariadb/conf.d:/etc/mysql/conf.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    env_file: .env
    ports:
      - $PHPMYADMIN_LISTEN_PORT:80
    volumes:
      - ./phpmyadmin/sessions:/var/lib/php7/session
    depends_on: 
      - mariadb

  apache:
    env_file: .env
    build:
      context: .
      dockerfile: ./php/Dockerfile
    ports:
      - $APACHE_LISTEN_PORT:80
    volumes:
      - $PUBLIC_DIR:/var/www/html
      - ./apache2/sites-available:/etc/apache2/sites-available
    depends_on: 
      - mariadb
